name: NewYearAmazingNight2024
version: ${version}
main: cn.xor7.NewYearAmazingNight
api-version: "1.20"
authors:
  - MC_XiaoHei
dependencies:
  server:
    ParticleLib:
      load: BEFORE
      required: true
    CommandAPI:
      load: BEFORE
      required: true